language: python
# Existing Python versions
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: required
before_install: pip install pipenv
install: pipenv install
script:
  - pip install pylint
  - pylint reposit --rcfile .pylintrc
  - pip install xenon
  - xenon -b B -m A -a A . 
  - pytest
