language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
before_install: pip install pipenv
install: pipenv install
script:
  - pip install pylint
  - pylint reposit --rcfile .pylintrc
  - pip install xenon
  - xenon -b B -m A -a A
  - pytest
